Os759405 6/api connect
alyonastartseva/kata-dns-store pull request #10
Opened 2023-10-19 13:46 UTC by krioplas

Closes Os759405-6/api connect

2023-10-19 21:04 UTC, nllchik approved these changes

2023-10-20 09:30 UTC, Konstantin-O-B commented on src/services/apiSlice.ts
> +    baseUrl: "test",
baseUrl же нам известна? Может лучше ее сразу указать?

2023-10-20 09:30 UTC, Konstantin-O-B commented on src/services/endpoints/injectEndpoints.ts
Наверное, лучше сделать комментарии в твоей доке со ссылкой на документацию RTK Query.
а то я потупил немного, но после документации все стало ясно

2023-10-20 10:07 UTC, Konstantin-O-B approved these changes

2023-10-20 10:12 UTC, Konstantin-O-B commented on src/services/apiSlice.ts
> +});
Лишние });

2023-10-24 11:13 UTC, alyonastartseva requested changes

2023-10-24 11:13 UTC, alyonastartseva commented on src/services/apiSlice.ts
> +    baseUrl: "http://localhost:8000/",
baseUrl лучше вынести в константу

2023-10-24 11:13 UTC, alyonastartseva commented on src/services/endpoints/injectEndpoints.ts
> +export const testApi = apiSlice.injectEndpoints({
а почему через инжектирование, а не в createApi эндпоинты описать?

2023-10-24 11:27 UTC, krioplas commented on src/services/endpoints/injectEndpoints.ts
> +export const testApi = apiSlice.injectEndpoints({
Подумал при расширении API будет удобно делать разные inject. Нагрузки не дает, но в будущем гораздо удобнее.

2023-10-24 11:30 UTC, krioplas commented on src/services/apiSlice.ts
> +    baseUrl: "http://localhost:8000/",
Вынес.

2023-10-24 17:55 UTC, alyonastartseva requested changes

2023-10-24 17:55 UTC, alyonastartseva commented on src/services/apiSlice.ts
> +    getShops: builder.query<void, void>({
опиши ещё, плиз, для getShops возвращаемый интерфейс

2023-10-25 22:41 UTC, alyonastartseva approved these changes

2023-10-26 05:10 UTC, merged