create extended promotion card layout
alyonastartseva/kata-dns-store pull request #12
Opened 2023-10-23 23:08 UTC by RomanTukhlin

2023-10-25 11:55 UTC, Konstantin-O-B commented on src/components/CountdownTimer/CountdownTimer.tsx
> +  const formatTimeLabel = (value: number, unit: "день" | "час" | "минута") => {
Я бы вынес функцию куда-нибудь в utility, или сделал отдельный хук

2023-11-03 21:14 UTC, alyonastartseva requested changes

2023-11-03 21:14 UTC, alyonastartseva commented on src/components/CountdownTimer/CountdownTimer.tsx
> +const TimeView: React.FC<{ time: TTimeObject }> = ({ time }) => {
лучше вынести в отдельный файлик

2023-11-03 21:14 UTC, alyonastartseva commented on src/components/CountdownTimer/CountdownTimer.tsx
> +  const formatTime = (time: number) => {
лучше будет вынести в shared-слой, тк может потребоваться в других компонентах - shared/utils/dates

2023-11-03 21:14 UTC, alyonastartseva commented on src/components/ExtendedPromotionCard/ExtendedPromotionCard.tsx
> +const ActionTerms: React.FC = () => {
это тоже лучше в двух разных положить

2023-11-03 21:14 UTC, alyonastartseva commented on src/shared/components/ShareButton/ShareButton.module.scss
> +  }
цветы в переменные

2023-11-03 21:14 UTC, alyonastartseva commented on src/shared/components/ShareContent/ShareContent.module.scss
> +  display: flex;
тоже переменных не хватает

2023-11-07 23:03 UTC, alyonastartseva approved these changes

2023-11-09 02:51 UTC, merged