final sidebar promotions
alyonastartseva/kata-dns-store pull request #14
Opened 2023-10-25 14:42 UTC by krioplas

Closes OS759405-11 - Верстка sidebar'а страницы "Акции"

2023-10-26 18:58 UTC, PlymBum commented on src/components/actionPageSaidbar/ActionPageSaidbar.module.scss
> +  background-color: #fff;
цвета лучше вынести в переменные. Будет правка от Алены)

2023-10-27 07:24 UTC, krioplas commented on src/components/actionPageSaidbar/ActionPageSaidbar.module.scss
> +  background-color: #fff;
Поправил.

2023-10-27 15:46 UTC, nllchik approved these changes

2023-10-30 08:12 UTC, PlymBum approved these changes

2023-10-31 12:35 UTC, alyonastartseva requested changes

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.module.scss
> +  padding: 0 !important;
давай уберем important

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +function getItem(
почему через геттер, а не просто массив объектов?

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +  getItem("Распродажа", "sub10", [
файл компонента "раздувается" из-за больших констант, давай рядом положим ActionPageSideBar.constants.ts

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +import React from "react";
опечатка в названии папки компонента и файликах в нем

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +    { lable: "Все акции", htmlId: "actions" },
все , что не меняется и не используется в компоненте - выносить из него

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +  const promotion: any = typePromotion.map((el) => {
избегаем any

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +      <CustomCheckbox lable={el.lable} htmlId={el.htmlId} key={el.lable} />
`{...el}`

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +  const manufacturer = [
аналогично - вынести за компоненту

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +  const manufacturerList: any = manufacturer.map((el) => {
any

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/CustomCheckbox.tsx
> +const CustomCheckbox = (props: any) => {
any!

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/CustomCheckbox.tsx
> +        {props.lable}
labEL

2023-10-31 12:35 UTC, alyonastartseva commented on src/components/actionPageSaidbar/CustomCheckbox.tsx
> +const CustomCheckbox = (props: any) => {
и можно сразу деструктуризировать - { label, htmlId }

2023-10-31 12:49 UTC, krioplas commented on src/components/actionPageSaidbar/ActionPageSaidbar.tsx
> +function getItem(
Так работает компонент в antd. Подумаю другие варианты если необходимо.

2023-10-31 13:16 UTC, krioplas commented on src/components/actionPageSaidbar/ActionPageSaidbar.module.scss
> +  padding: 0 !important;
Переделал important влияет теперь только н а сам компонент.

2023-11-03 20:56 UTC, alyonastartseva approved these changes

2023-11-05 04:28 UTC, merged