close OS759405-18/popover
alyonastartseva/kata-dns-store pull request #17
Opened 2023-10-27 15:01 UTC by nllchik

2023-10-27 22:55 UTC, PlymBum approved these changes

2023-10-28 09:38 UTC, Olegandrr approved these changes

2023-10-31 12:19 UTC, alyonastartseva requested changes

2023-10-31 12:19 UTC, alyonastartseva commented on src/components/CatalogButton/CatalogButton.tsx
> +      {catalogActive ? (
catalogActive &&

2023-10-31 12:19 UTC, alyonastartseva commented on src/components/HeaderMenuLink/HeaderMenuLink.tsx
> +        return (
return можно опустить

2023-10-31 12:19 UTC, alyonastartseva commented on src/components/CatalogButton/CatalogButton.tsx
> +          {!catalogActive ? <DownOutlined /> : <UpOutlined />}
не обязательно править, just comment: тернарники лучше писать всегда через true, условия с НЕ труднее читаются (но в этом случае не трудно :))

2023-10-31 12:52 UTC, alyonastartseva approved these changes

2023-10-31 13:14 UTC, merged