Close OS759405-21-add fonts
alyonastartseva/kata-dns-store pull request #21
Opened 2023-11-01 08:39 UTC by krioplas

Close OS759405-21-add fonts

2023-11-01 10:42 UTC, Olegandrr approved these changes

2023-11-01 11:09 UTC, RomanTukhlin approved these changes

2023-11-02 12:58 UTC, alyonastartseva requested changes

2023-11-02 12:58 UTC, alyonastartseva commented on src/styles/fonts.scss
> +html,
а через * можно?

2023-11-03 20:40 UTC, alyonastartseva approved these changes

2023-11-05 04:26 UTC, merged