Os759405 5/store map
alyonastartseva/kata-dns-store pull request #23
Opened 2023-11-01 11:39 UTC by nllchik

2023-11-01 11:41 UTC, PlymBum approved these changes

2023-11-01 12:43 UTC, Olegandrr approved these changes
из Layout страницу магазинов нужно удалить

2023-11-02 12:54 UTC, alyonastartseva requested changes

2023-11-02 12:54 UTC, alyonastartseva commented on src/components/Header/Header.module.scss
> +  // position: fixed;
закомментированное лучше сразу подчищать

2023-11-02 12:54 UTC, alyonastartseva commented on src/components/StoreMap/StoreMap.tsx
> +    if (selectedStore !== null) {
а если undefined?

2023-11-03 17:26 UTC, alyonastartseva approved these changes

2023-11-03 17:26 UTC, merged