OS759405-16 - create store page
alyonastartseva/kata-dns-store pull request #25
Opened 2023-11-07 07:48 UTC by RomanTukhlin

2023-11-07 13:20 UTC, PlymBum approved these changes

2023-11-07 13:20 UTC, PlymBum commented on src/components/CatalogButton/CatalogButton.module.scss
> +      background: rgba(255, 255, 255, 0.12);
цвета не в переменных

2023-11-07 13:20 UTC, PlymBum commented on src/components/PaymentMethonds/PaymentMethonds.tsx
> +import { nanoid } from "nanoid";
скорее всего будет всегда уникальный id, лучше использовать что-то с сервера

2023-11-07 13:20 UTC, PlymBum commented on src/components/StoreMap/StoreMap.tsx
> +
коменты

2023-11-07 13:20 UTC, PlymBum commented on src/routes/mainRoutes.tsx
> +    { path: "/shops/:slug", element: <StorePage /> },
:slug поменял бы на :shop или :shopId

2023-11-07 20:44 UTC, Olegandrr approved these changes

2023-11-08 21:41 UTC, alyonastartseva requested changes

2023-11-08 21:41 UTC, alyonastartseva commented on src/index.tsx
> -  <React.StrictMode>
поч StrictMode убрал?

2023-11-08 21:41 UTC, alyonastartseva commented on src/pages/StorePage/StorePage.tsx
> +  const { data } = useGetShopsQuery("");
`useGetShopsQuery()`

2023-11-08 21:41 UTC, alyonastartseva commented on src/shared/components/FeedbackForm/FeedbackForm.type.ts
> +  name: string | undefined;
`name?: string;`

(ниже тоже самое)

2023-11-08 21:41 UTC, alyonastartseva commented on src/shared/components/ShowMore/ShowMore.type.ts
> +  children?: string | ReactNode | undefined;
undefined можно убрать

2023-11-08 21:43 UTC, alyonastartseva commented
хорошо разделил по компонентам 👍🏻 
поправь типы с undefined, решай конфликты и можно мержить

2023-11-09 02:54 UTC, RomanTukhlin commented on src/index.tsx
> -  <React.StrictMode>
Со StrictMode ошибка от компонента Popover из antd

2023-11-09 04:49 UTC, RomanTukhlin commented on src/index.tsx
> -  <React.StrictMode>
Там при StrictMode была ошибка(findDOMNode устарел в StrictMode. ) от компонента Popover из antd

2023-11-09 10:06 UTC, alyonastartseva approved these changes

2023-11-09 10:07 UTC, merged