Closes Os759405-3 Добавление husky, eslint и prettier
alyonastartseva/kata-dns-store pull request #3
Opened 2023-10-15 07:49 UTC by PlymBum

2023-10-15 08:12 UTC, nllchik approved these changes

2023-10-15 08:59 UTC, Konstantin-O-B commented on eslintrc.cjs
> +  plugins: ['react', 'jsx-a11y', 'import', 'react-refresh', 'unicorn', 'jsx-a11y'],
По доке еще этот плагин добавить надо если решили с TS работать. Поправь меня, если я неправильно понял доку)
plugins: ['@typescript-eslint']
https://typescript-eslint.io/getting-started/#:~:text=plugins%3A%20%5B%27%40typescript%2Deslint%27%5D%2C

2023-10-15 09:03 UTC, Konstantin-O-B commented on eslintrc.cjs
> +  plugins: ['react', 'jsx-a11y', 'import', 'react-refresh', 'unicorn', 'jsx-a11y'],
По доке еще этот плагин добавить надо если решили с TS работать. Поправь меня, если я неправильно понял доку)
plugins: ['https://github.com/typescript-eslint']
https://typescript-eslint.io/getting-started/#:~:text=plugins%3A%20%5B%27%40typescript%2Deslint%27%5D%2C

2023-10-15 09:24 UTC, PlymBum commented on eslintrc.cjs
> +  plugins: ['react', 'jsx-a11y', 'import', 'react-refresh', 'unicorn', 'jsx-a11y'],
Добавил

2023-10-15 09:29 UTC, Konstantin-O-B approved these changes

2023-10-16 18:40 UTC, alyonastartseva requested changes

2023-10-16 18:40 UTC, alyonastartseva commented on package.json
> +    "*.(js|jsx)": [
Очепятка расширений

2023-10-16 18:43 UTC, PlymBum commented on package.json
> +    "*.(js|jsx)": [
поправил

2023-10-16 18:45 UTC, alyonastartseva approved these changes

2023-10-16 18:46 UTC, merged