Create store page
alyonastartseva/kata-dns-store pull request #4
Opened 2023-10-17 11:22 UTC by Konstantin-O-B

2023-10-17 14:46 UTC, nllchik commented
1. В компоненте FilterButtons отсутствуют ключи (key) у кнопок 'Список' и 'Карта', что вызывает ошибку в консоли. 
2. Думаю стоит отцентровать всю страницу (сейчас прижата к левому краю).

2023-10-17 16:05 UTC, nllchik approved these changes

2023-10-17 18:24 UTC, RomanTukhlin approved these changes

2023-10-19 13:39 UTC, alyonastartseva requested changes

2023-10-23 19:10 UTC, alyonastartseva commented on src/components/FilterButtons/FilterButtons.module.css
файлик остался

2023-10-23 19:13 UTC, alyonastartseva commented on src/hooks/useFocus.ts
> +const useFocus = (): [boolean, () => void, (e: React.FocusEvent<HTMLInputElement>) => void] => {
как решение - в целом - норм
но говорила про вот такое https://hooks-guide.netlify.app/community/useFocus

2023-10-23 19:15 UTC, alyonastartseva commented on src/shared/components/FilterButton/FilterButton.tsx
> +type IButton = {
type, но называется с I? :)

2023-10-23 19:15 UTC, alyonastartseva commented on src/shared/components/FilterButton/FilterButton.tsx
> +    return <button
return можно опустить

2023-10-23 19:16 UTC, alyonastartseva commented on src/shared/components/FilterButton/FilterButton.tsx
> +type IButton = {
с I обычно называют интерфейсы
хотя сейчас уже считается пережитком прошлого именовать интерфейсы как IExample, а типы как TExample

2023-10-23 19:16 UTC, alyonastartseva commented on src/shared/components/SearchInput/SearchInput.tsx
> +/*     const [isFocused, setIsFocused] = useState(false);
подчистить

2023-10-24 18:54 UTC, Konstantin-O-B commented on src/shared/components/FilterButton/FilterButton.tsx
> +type IButton = {
> с I обычно называют интерфейсы хотя сейчас уже считается пережитком прошлого именовать интерфейсы как IExample, а типы как TExample

какую модель именования используют сейчас для типов и интерфейсов?

2023-10-25 22:13 UTC, alyonastartseva commented on src/shared/components/FilterButton/FilterButton.tsx
> +type IButton = {
просто Example, ExampleProps и т.д

2023-10-25 22:16 UTC, alyonastartseva approved these changes

2023-10-25 22:16 UTC, merged