close OS759405-9/pagination
alyonastartseva/kata-dns-store pull request #5
Opened 2023-10-18 10:47 UTC by PlymBum

[docs](https://wika.kata.academy/pages/viewpage.action?pageId=4063649)

2023-10-18 11:29 UTC, nllchik approved these changes

2023-10-18 13:08 UTC, Konstantin-O-B approved these changes

2023-10-23 20:17 UTC, alyonastartseva requested changes

2023-10-23 20:17 UTC, alyonastartseva commented on src/types/pagination.ts
> +export interface IPaginationProps {
зачем два одинаковых интерфейса?

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.module.scss
> +  border: 1px solid #f2f2f2;
все цвета лучше вынести в переменные

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +export const Pagination: FC<IPaginationProps> = ({
хм, а зачем через дженерик и отдельно пропсы типизировать?

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +    current < 1 || current > totalPage ? 1 : current,
1 в данном случае магическая константа

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +  const pages: number[] = [];
почему не состоянием хранить?

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +  if (currentPage < 5) {
5, 8, 7, 3, 4 и т.д - тоже магические константы

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +    for (let i = 1; i <= (totalPage < 8 ? totalPage : 8); i++) {
```
const arrayRange = (start, stop, step) =>
    Array.from(
    { length: (stop - start) / step + 1 },
    (value, index) => start + index * step
    );
``` 
альтернатива как сократить повторяющийся код
к тому же, такую функцию можно вынести в helpers и использовать в других местах (где потребуется)

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +  const onClick = (page: number): void => {
`void` необязательно писать - он по-умолчанию у функций

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +    setCurrentPage((prev) => prev + 1);
`prev++`

2023-10-23 20:17 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +    setCurrentPage((prev) => prev - 1);
`prev--`

2023-10-24 11:23 UTC, alyonastartseva requested changes

2023-10-24 11:23 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +  const createArrayPages = (lastPage:number) =>
имела ввиду вынести эту функцию в shared/utils, которая принимала бы start, stop и step

2023-10-24 11:23 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +  const createArrayPages = (lastPage:number) =>
а здесь её заиспользовать

2023-10-24 11:23 UTC, alyonastartseva commented on src/components/Pagination/Pagination.tsx
> +    }else if(currentPage>totalPage-(showedPage -1)){
условие справа вынести бы в переменную - сходу не понять

2023-10-24 11:37 UTC, PlymBum commented on src/components/Pagination/Pagination.tsx
> +  const createArrayPages = (lastPage:number) =>
а идеально, если эту логику вынести в функцию (которая останется в компоненте), дать ей осмысленное название (чтоб сходу читалось) и вызвать в useEffect'е

сделал отдельную функцию и оставил в компоненте.  Плюс упростил ее именно для пагинации, чтоб не принимала лишних парраметров.  Или что-то не правильно понял?

2023-10-25 22:19 UTC, alyonastartseva approved these changes

2023-10-25 22:19 UTC, merged