Os759405 1/header layout
alyonastartseva/kata-dns-store pull request #8
Opened 2023-10-19 01:18 UTC by RomanTukhlin

2023-10-19 05:19 UTC, krioplas approved these changes

2023-10-19 05:19 UTC, krioplas commented on src/components/ProductSearchInput/ProductSearchInput.tsx
> +const getRandomInt = (max: number, min = 0) =>
Может такие утилиты будем выносить в отдельную папку utils? так как их можно использовать в нескольких местах, при необходимости.

2023-10-19 09:06 UTC, PlymBum reviewed
Пропадает все меню кроме поиска и города при уменьшении разрешения.

2023-10-19 09:17 UTC, PlymBum approved these changes

2023-10-24 10:51 UTC, alyonastartseva requested changes

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/CatalogButton/CatalogButton.tsx
> +  const handleClick = (): void => {
void можно опустить - функции по-умолчанию типа void

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/Header/Header.module.scss
> +.header {
пустой селектор

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/Header/Header.tsx
> +          style={{ paddingTop: 20, paddingBottom: 20 }}
лучше инлайновые стили не использовать, а писать в одном месте - в нашем случае в scss (относится ко всему файлу)

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/HeaderMenuLink/HeaderMenuLink.tsx
> +      <MenuLink to="#">Акции</MenuLink>
будет здорово, есть все Menu Link вынести в массив объектов и замаппить

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/ProductSearchInput/ProductSearchInput.module.scss
> +
в этом файле тоже причесать important

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/ProductSearchInput/ProductSearchInput.tsx
> +const searchResult = (query: string) =>
утилитки для компонента можно складывать рядом (чтобы не увеличивать файл самого компонента) - [helpers | utils].ts

2023-10-24 10:51 UTC, alyonastartseva commented on src/components/ProductSearchInput/ProductSearchInput.tsx
> +              display: "flex",
инлайновые стили везде проверить и переправить на scss

2023-10-24 10:51 UTC, alyonastartseva commented on src/shared/components/DropdownLink/DropdownLink.module.scss
> +        background: transparent !important;
important тоже проверить везде

2023-10-25 22:30 UTC, alyonastartseva approved these changes

2023-10-25 23:57 UTC, merged